[STUDYLION]
token = REPLACE_WITH_DISCORD_BOT_TOKEN

[DATA]
args = dbname=gostudy user=gostudy password=REPLACE_WITH_DATABASE_PASSWORD host=127.0.0.1
appid = GoStudy

[TOPGG]
auth = REPLACE_WITH_TOPGG_TOKEN_IF_ENABLED
